version: 0.2

phases:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 316972670200.dkr.ecr.us-east-1.amazonaws.com
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t myrepo .
      - docker tag myrepo:latest 316972670200.dkr.ecr.us-east-1.amazonaws.com/myrepo:latest
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 316972670200.dkr.ecr.us-east-1.amazonaws.com/myrepo:latest
      - printf '[{"name":"democluster","imageUri":"316972670200.dkr.ecr.us-east-1.amazonaws.com/myrepo"}]' > imagedefinitions.json
      
artifacts:
  files:
    - imagedefinitions.json
